export function eu4_builder(mod, files, gameFolder) {
  console.log('EU4!')
  console.log(files)
  const songNames = files.map(f => {
    return f.name.split(".")[0]
  })

  const musicFolder = gameFolder.folder("music")
  musicFolder.file("Hello.txt", "Hello World\n");
  return gameFolder

  /*
  # MUSIC AUTOMATION TOOL (MAT) for Europa Universalis 4

  # This is a script that creates the required .asset file and a basic .txt file for your Europa Universalis 4 Music Mod based on the .ogg files passed into it.
  
  # The script will skip over any file called "maintheme" as this only replaces the loading music and is not shown in-game by the audio engine.
  # The script also allows for your files to be prefixed with a number and an underscore, e.g. 1_Pokemon.ogg, 2_YuGiOh.ogg, so that you can order your music tracks.
  # You are strong encouraged to hop into the generated files and check that everything has been created properly. In particular, you may wish to add to the conditions in the .txt file that affect the chances of the music playing.
  
  # This script is open-source and was created by Runite Drill for ease in publishing music mods by community composer Utopia.
  # Feel free to join their music modding community and ask any questions: https://discord.gg/SdQhfBM
  
  # For more info/guide on music modding, please visit the EU4 wiki: https://eu4.paradoxwikis.com/Music_modding
  */
  
  const asset_header = `
  #This file was automatically generated by the Music Automation Tool (MAT), created by Runite Drill / Utopia.
  #Consider joining the music modding discord server, Utopia, if you have any questions: https://discord.gg/SdQhfBM.
  
  #Please confirm the output is as expected before testing in-game.
  
  `
  const asset_def = `
  
  music = {
      name = "${files}"
      file = "${files}"
  `
  
  const txt_header = `
  #This file was automatically generated by the Music Automation Tool (MAT), created by Runite Drill.
  #Consider joining the music modding discord server, Utopia, if you have any questions: https://discord.gg/SdQhfBM.
  
  #In this file you can specific the triggers and conditions in which the music will play in-game.
  #Consult the music modding page on the EU4 wiki for more info: https://eu4.paradoxwikis.com/Music_modding.
  #Please confirm the output is as expected before testing in-game.
  
  `
  
  const txt_def = `
  
  song = {
      name = "%s"
      chance = {
          modifier = { factor = 1 }
      }
  }
  
  `
  
  // songlist = dict()
  
  // for file in files:
  //     prefix = -1
  //     if (x := file[: file.find("_")]) and x.isdecimal():
  //         prefix = int(x)
  //         name = file[file.find("_") + 1 : file.rfind(".")]
  //     else:
  //         name = file[: file.rfind(".")]
  //     if not name:
  //         print(f"File missing proper name: '{file}'.")
  //         continue
  //     if name == "maintheme":
  //         print("New main theme detected. Will not be written to music mod files.")
  //         continue
  //     if name in songlist:
  //         print(f"Duplicate song name: '{name}'. Please ensure that each song is unique.")
  //         continue
  //     songlist[name] = (file, prefix)
  
  // songlist = {k: v[0] for k, v in sorted(songlist.items(), key=(lambda k: float("inf") if k[1][1] == -1 else k[1][1]))}
  
  // print("Creating .asset file...")
  // with open(path.join(PATH, f"MAT-{mod}-EU4.asset"), "w") as f:
  //     f.write(asset_header)
  //     for name, file in songlist.items():
  //         f.write(asset_def % (name, file))
  
  // print("Creating .txt file...")
  // with open(path.join(PATH, f"MAT-{mod}-EU4.txt"), "w") as f:
  //     f.write(txt_header)
  //     for name in songlist:
  //         f.write(txt_def % name)
  
  // input("Done!")



  return
}