export function ir_builder(mod, files, gameFolder) {
  /*
  # MUSIC MOD CREATION TOOL (MMCT) for Imperator: Rome

  # This is a script that creates the required .asset file and a basic .txt file for your Imperator: Rome Music Mod based on the .ogg files passed into it.
  
  # The script will skip over any file called "maintheme" as this only replaces the loading music and is not shown in-game by the audio engine.
  # You are strongly encouraged to hop into the generated files and check that everything has been created properly. In particular, you may wish to add to the conditions in the .txt file that affect the chances of the music playing.
  
  # This script is open-source and was created by community composer Runite Drill / Utopia for ease in publishing music mods.
  # Feel free to join their music modding community and ask any questions: https://discord.gg/SdQhfBM
  
  # For more info/guide on music modding, please visit the EU4 wiki: https://imperator.paradoxwikis.com/Music_modding
  */

  console.log('IR!')
  const musicFolder = gameFolder.folder("music")

  //Create .txt file
  const text = [textHeader]
  files.forEach((f) => {
    if (f.name.split(".")[0] !== "maintheme") {
      text.push(textDef(f))
    }
    musicFolder.file(f.name, f)
  })
  musicFolder.file(`${mod}_MMCT.txt`, text.join('\n'));

  return gameFolder
}

const textHeader = `#This file was automatically generated by the Music Mod Creation Tool (MMCT), created by Runite Drill / Utopia.
#Consider joining the music modding discord server, Utopia, if you have any questions: https://discord.gg/SdQhfBM.
#Use the Music Mod Creation Tool to generate your own music mods for all Paradox Interactive games: <link tba>
  
#Please confirm the output is as expected before testing in-game.

#Unfortunately, Imperator: Rome does not support custom triggers, factors and conditions to alter the chance at which the music will play in-game.
#The 'weight' factor is a user-defined measure of how "heavy" the music is. When a song is played, its weight is added to a global counter. When that global counter reaches 100 it resets and the game pauses all music for a short period of time. This is give the listener some respite from any chain of potentially oerhwelming music tracks.
#'can_be_interrupted' determines whether the music track can be overriden by other music, such as event-triggered music.
#Consult the music modding page on the IR wiki for more info: https://imperator.paradoxwikis.com/Music_modding.
`

function textDef(file) {
  return `${file.name.split(".")[0]}_MMCT = {
    music = file:/music/${file.name}
    weight = 15
    mood = yes
    can_be_interrupted = yes
}\n`
}